Added ASCII entry
FSipiano/newbieDictionary pull request #11
Opened 2020-10-19 15:03 UTC by san-damian

Just adding a little entry about ASCII meaning

2020-10-19 15:53 UTC, FSipiano requested changes
Please fix the typo and I can merge

2020-10-19 15:53 UTC, FSipiano commented on README.md
> +**ASCII** - Stands for 'American Standart Code for Information Interchage'. It is the set of common characters use in electronic communication, based in English alphabet, numbers, punctuation symbols
Is this a typo - standart?

2020-10-19 17:22 UTC, san-damian commented on README.md
> +**ASCII** - Stands for 'American Standart Code for Information Interchage'. It is the set of common characters use in electronic communication, based in English alphabet, numbers, punctuation symbols
Sorry, my bad

2020-10-20 08:09 UTC, FSipiano commented on README.md
> +**ASCII** - Stands for 'American Standart Code for Information Interchage'. It is the set of common characters use in electronic communication, based in English alphabet, numbers, punctuation symbols
No worries, thanks for fixing!

2020-10-20 08:10 UTC, FSipiano approved these changes
Perfect, thanks. Please create a pull request and I can merge

2020-10-20 10:14 UTC, merged